{% set name = "anyio" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 4a41c5b3a65ed92e469d51b6fba3779301850ea2e352afcf9e36c46f21ee14a9
  - folder: src
    url: https://github.com/agronholm/{{ name }}/archive/{{ version }}.tar.gz
    sha256: c1b748c399cc1051af7663d9765777d695534c17943285403c5bce993a34cd20

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - async_generator  # [py<37]
    - dataclasses  # [py<37]
    - idna >=2.8
    - python
    - sniffio >=1.1
    - typing_extensions  # [py<38]
  run_constrained:
    - trio >=0.16
    - curio >=1.4

test:
  source_files:
    - src/tests
  requires:
    - coverage >=4.5
    - curio
    - hypothesis >=4.0
    - pip
    - pytest >=6.0
    - pytest-cov
    - toml
    - trio
    - trustme
    # TODO: won't be available on pypy
    - uvloop  # [unix and python_impl == 'cpython']
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
