{% set version = "4.5.0" %}

package:
  name: anyio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/anyio/anyio-{{ version }}.tar.gz
  sha256: c5a275fe5ca0afd788001f58fca1e69e29ce706d746e317d660e21f70c530ef9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=6.4
  run:
    - exceptiongroup >=1.0.2
    - idna >=2.8
    - python >=3.8
    - sniffio >=1.1
    - typing_extensions >=4.1
  run_constrained:
    - trio >=0.26.1
    - uvloop >=0.21.0b1

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - coverage >=7
    - exceptiongroup >=1.2.0
    - hypothesis >=4.0
    - mock >=4
    - pip
    - psutil >=5.9
    - pytest >=7.0
    - pytest-mock >=3.6.1
    - tomli
    - trio
    - trustme
    # TODO restore after https://github.com/conda-forge/anyio-feedstock/issues/64
    # # won't be available on pypy, or windows, any time soon
    # - uvloop  # [unix and python_impl == 'cpython']
  imports:
    - anyio
  commands:
    - coverage run --source anyio --branch -m pytest -k="not (bind_link_local or block_device or connection_refused or happy_eyeballs or ipv6)"
    - coverage report --show-missing --skip-covered --fail-under 87  # [linux]

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
    - CJ-Wright
    - dhirschfeld
