{% set name = "anyio" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 85913b4e2fec030e8c72a8f9f98092eeb9e25847a6e00d567751b77e34f856fe
  - folder: src
    url: https://github.com/agronholm/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 2f27663b77aa484ca85544f6701f7d6710e9cf4fbb23df0990c8447983aabb32

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - async_generator  # [py<37]
    - dataclasses  # [py<37]
    - idna >=2.8
    - python
    - sniffio >=1.1
    - typing_extensions  # [py<38]
  run_constrained:
    - trio >=0.16

test:
  source_files:
    - src/tests
    - src/pyproject.toml
  requires:
    - coverage >=4.5
    - trio
    - hypothesis >=4.0
    - mock >=4
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - toml
    - trustme
    # won't be available on pypy, or windows, any time soon
    - uvloop  # [unix and python_impl == 'cpython']
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
