{% set name = "anyio" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 35075abd32cf20fd7e0be2fee3614e80b92d5392eba257c8d2f33de3df7ca237
  - folder: src
    url: https://github.com/agronholm/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 2439f9d71d793d72d4e223632b9ef8beafc021989efac7b049f0c73280322d2a

build:
  number: 1
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - async_generator  # [py<37]
    - dataclasses  # [py<37]
    - idna >=2.8
    - python
    - sniffio >=1.1
    - typing_extensions  # [py<38]
  run_constrained:
    - trio >=0.16
    - curio >=1.4

test:
  source_files:
    - src/tests
  requires:
    - coverage >=4.5
    - curio
    - hypothesis >=4.0
    - pip
    - pytest >=6.0
    - pytest-cov
    - toml
    - trio
    - trustme
    # TODO: won't be available on pypy
    - uvloop  # [unix]
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
