{% set version = "4.0.0" %}

package:
  name: anyio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/a/anyio/anyio-{{ version }}.tar.gz
    sha256: f7ed51751b2c2add651e5747c891b47e26d2a21be5d32d9311dfe9692f3e5d7a
  - folder: src
    url: https://github.com/agronholm/anyio/archive/{{ version }}.tar.gz
    sha256: 518a6f319b174b5b7de126ae983035d2205df4ef0f39eb23ac4139cbb1bf3c49

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=6.4
  run:
    - exceptiongroup
    - idna >=2.8
    - python >=3.8
    - sniffio >=1.1
    - typing_extensions
  run_constrained:
    - trio >=0.22

test:
  source_files:
    - src/tests
    - src/pyproject.toml
  requires:
    - coverage >=7
    - trio
    - hypothesis >=4.0
    - mock >=4
    - pip
    - psutil >=5.9
    - pytest >=7.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - toml
    - trustme
    # won't be available on pypy, or windows, any time soon
    - uvloop >=0.17  # [unix and python_impl == 'cpython']
  imports:
    - anyio
  commands:
    - pip check

about:
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  doc_url: https://anyio.readthedocs.io
  doc_source_url: https://github.com/agronholm/anyio/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
    - davidbrochart
