# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.12.0"
  python_check_max: "3.14"

package:
  name: anyio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/anyio/anyio-${{ version }}.tar.gz
  sha256: 73c693b567b0c55130c104d0b43a9baf3aa6a31fc6110116509f27bf75e21ec0

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=6.4
  run:
    - exceptiongroup >=1.0.2
    - idna >=2.8
    - python >=${{ python_min }}
    - typing_extensions >=4.5
  run_constraints:
    - trio >=0.32.0
    - uvloop >=0.21

tests:
  - python:
      imports: anyio
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - coverage >=7
        - exceptiongroup >=1.2.0
        - hypothesis >=4.0
        - psutil >=5.9
        - pytest >=7.0
        - pytest-mock >=3.14
        - python ${{ python_min }}.*
        - python-blockbuster >=1.5.23
        - tomli
        - trio
        - trustme
        - truststore >=0.9.1
        - if: unix
          then:
            - uvloop
    script:
      env:
        PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      file: run_test.py

about:
  license: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  homepage: https://github.com/agronholm/anyio
  documentation: https://anyio.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - CJ-Wright
    - dhirschfeld
