# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.9.0

package:
  name: anyio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/anyio/anyio-${{ version }}.tar.gz
  sha256: 673c0c244e15788651a4ff38710fea9675823028a6f08a5eda409e0c9840a028

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=6.4
  run:
    - exceptiongroup >=1.0.2
    - idna >=2.8
    - python >=${{ python_min }}
    - sniffio >=1.1
    - typing_extensions >=4.5
  run_constraints:
    - trio >=0.26.1
    - uvloop >=0.21

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: anyio
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - coverage >=7
        - exceptiongroup >=1.2.0
        - hypothesis >=4.0
        - psutil >=5.9
        - pytest >=7.0
        - pytest-mock >=3.6.1
        - python ${{ python_min }}.*
        - python-blockbuster >=1.5.23
        - tomli
        - trio
        - trustme
        - if: unix
          then:
            - uvloop
    script:
      env:
        PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      content:
        - python run_test.py

about:
  license: MIT
  license_file: LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations on Python
  homepage: https://github.com/agronholm/anyio
  documentation: https://anyio.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - CJ-Wright
    - dhirschfeld
